name = "glrx"
version = "0.1.0"
licences = ["MIT"]
description = "Reactive extensions for Gleam"
repository = { type = "github", user = "kvdos-argonaut", repo = "glrx" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.18"

[dev-dependencies]
gleeunit = "~> 0.5"
